# Sample .travis.yml for R projects


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev


language: r
warnings_are_errors: true
sudo: required

r_binary_packages:
  - rgdal