# from https://github.com/MartinRoth/knmiR/blob/master/.travis.yml
branches:
  only:
    - master
    - develop

language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
