before_install:
  - pwd
  - export CURWD=`pwd`
  - cd
  - sudo apt-get install libproj-dev
  - wget http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  - tar zxf gdal-1.11.2.tar.gz
  - cd gdal-1.11.2
  - ./configure
  - make
  - sudo make install
  - cd $CURWD


#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
#  - sudo apt-get update
#  - sudo apt-get install libgdal-dev


language: r
warnings_are_errors: true
sudo: required



